"""empty message

Revision ID: b68ce4f75bea
Revises: dfdb044dfc52
Create Date: 2018-05-12 17:40:51.151206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68ce4f75bea'
down_revision = 'dfdb044dfc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('mobile_number', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_agent_email'), 'alert_agent', ['email'], unique=True)
    op.create_index(op.f('ix_alert_agent_mobile_number'), 'alert_agent', ['mobile_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_agent_mobile_number'), table_name='alert_agent')
    op.drop_index(op.f('ix_alert_agent_email'), table_name='alert_agent')
    op.drop_table('alert_agent')
    # ### end Alembic commands ###
